# conf/setup_pll_pinn.yaml
defaults:
  - params_pll
  - setup_pll_dataset      # 先读数据集的配置
  - override hydra.run.dir: ${hydra:runtime.cwd}/outputs/${now:%Y-%m-%d}/${hydra.job.name}

wandb:
  api_key: "c26f0418182418f6712b79b4457de4faa81b7524"
  project: "PLL-ROM"

# 数据集部分沿用上一个文件配置，不需要改

physics: ${params_pll}

# PINN 网络及优化器配置
nn:
  type: "DynamicNN"
  input_dim: 3
  output_dim: 2
  activation:   "tanh"
  learning_rate: 0.01
  weight_data: 1.0      # λd
  weight_pde_data: 0.02    # λpd   ← 新增
  weight_pde_col: 0.03     # λpc
  weight_ic: 5   # λic
  hidden_dim: 64
  hidden_layers: 4
  loss_criterion: "MSELoss"
  optimizer: "Adam"
  weight_init: "xavier_normal"
  lr: 1e-4
  lr_scheduler: "No_scheduler"
  num_epochs: 15000
  batch_size: 128
  early_stopping: true
  early_stopping_patience: 2500
  early_stopping_min_delta: 1e-6

#  weighting:
#    flag_mean_weights: true
#    update_weight_method: "Static"
#    update_weights_freq: 50
#    weights: [ 1, 1e-3, 1e-4, 1e-3 ]

# 如果你的 DataSampler 或者训练脚本还用到以下几个字段，也一并写上
dataset:
  # perc_of_data、split_ratio、validation_flag 已从 setup_pll_dataset 继承
  perc_of_col_points: 1.0

